[package]
name = "reflectionnnn/spring"
description = "Simple spring module."
license = "MIT"
authors = ["Reflection"]
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "LICENSE"]

[dependencies]
