[package]
name = "reflectionnnn/spring"
description = "Closure spring physics module."
license = "MIT"
authors = ["Reflection"]
version = "2.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["lib", "LICENSE"]

[dependencies]